shellEmulator: true
trustPolicy: off
packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalog:
  cac: ^7.0.0
  consola: ^3.4.2
  cross-spawn: ^7.0.6
  dotenv: ^17.4.2
  dotenv-expand: ^13.0.0
  kolorist: ^1.8.0
  local-pkg: ^1.2.1
  pathe: ^2.0.3
  std-env: ^3.10.0
  strip-ansi: ^7.2.0
  unconfig: ^7.5.0
catalogs:
  cli:
    '@antfu/eslint-config': ^9.0.0
    bumpp: ^11.1.0
    eslint: ^10.4.1
    lint-staged: ^17.0.7
    simple-git-hooks: ^2.13.1
    tsdown: ^0.22.2
    typescript: ^6.0.3
  testing:
    vitest: ^3.2.6
    vitest-package-exports: ^1.2.0
  types:
    '@types/cross-spawn': ^6.0.6
    '@types/node': ^24.13.1
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
