packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalog:
  '@uni-helper/uni-env': ^0.2.0
  cac: ^6.7.14
  consola: ^3.4.2
  cross-spawn: ^7.0.6
  dotenv: ^17.2.3
  dotenv-expand: ^12.0.3
  fs-extra: ^11.3.2
  kolorist: ^1.8.0
  local-pkg: ^1.1.2
  moment: ^2.30.1
  pathe: ^2.0.3
  std-env: ^3.10.0
  unconfig: ^7.3.3
catalogs:
  cli:
    '@antfu/eslint-config': ^4.10.1
    bumpp: ^10.1.0
    eslint: ^9.22.0
    lint-staged: ^16.1.6
    simple-git-hooks: ^2.11.1
    tsdown: ^0.16.4
    typescript: ^5.8.2
  testing:
    vitest: ^3.0.8
    vitest-package-exports: ^0.1.1
  types:
    '@types/cross-spawn': ^6.0.6
    '@types/fs-extra': ^11.0.4
    '@types/node': ^22.13.10
  utils:
    tinyexec: ^0.3.2
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
