packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalog:
  blessed: ^0.1.81
  cac: ^6.7.14
  cross-spawn: ^7.0.6
  globby: ^15.0.0
  kolorist: ^1.8.0
  local-pkg: ^1.1.2
  unconfig: ^7.3.3
  yaml: ^2.8.1
catalogs:
  cli:
    '@antfu/eslint-config': ^4.10.1
    bumpp: ^10.1.0
    eslint: ^9.22.0
    lint-staged: ^16.1.6
    simple-git-hooks: ^2.11.1
    tsdown: ^0.14.2
    typescript: ^5.8.2
  testing:
    vitest: ^3.0.8
    vitest-package-exports: ^0.1.1
  types:
    '@types/blessed': ^0.1.25
    '@types/cross-spawn': ^6.0.6
    '@types/node': ^22.13.10
  utils:
    tinyexec: ^0.3.2
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
